### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by sleipnir**

### CODE REVIEW

**Comment by sleipnir** [comment]
ping @marcellanz @ralphlaude

**Comment by marcellanz** [comment]
Apache 2 ist fine for me.

**Comment by sleipnir** [comment]
Thank you @marcellanz , please approve the review so we can merge with Master

**Comment by ralphlaude** [comment]
Sorry :( @sleipnir I missed it

**Comment by sleipnir** [comment]
Don't worry @ralphlaude It's fine!

**Pull request merged**
